version: '3.8'

services:
  # Worker 1
  editly-worker1:
    container_name: editly-worker1
    image: editly/editly:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - "./outputs:/outputs"
      - "./uploads:/app/uploads"
      - "./temp:/app/temp"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - EXTERNAL_DOMAIN=https://editly.byinfant.com
      - USE_GPU=true
      - VIDEO_ENCODER=h264_nvenc
      - NVENC_PRESET=p1
      - NVENC_CQ=30
      - FFMPEG_THREADS=8
      - UV_THREADPOOL_SIZE=64
      - NODE_OPTIONS=--max-old-space-size=7168
      - WORKER_ID=worker1
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
    gpus: all
    command: ["node", "dist/api-server.js"]
    restart: unless-stopped
    networks:
      - editly-network

  # Worker 2
  editly-worker2:
    container_name: editly-worker2
    image: editly/editly:latest
    ports:
      - "3002:3001"
    volumes:
      - "./outputs:/outputs"
      - "./uploads:/app/uploads"
      - "./temp:/app/temp"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - EXTERNAL_DOMAIN=https://editly.byinfant.com
      - USE_GPU=true
      - VIDEO_ENCODER=h264_nvenc
      - NVENC_PRESET=p1
      - NVENC_CQ=30
      - FFMPEG_THREADS=8
      - UV_THREADPOOL_SIZE=64
      - NODE_OPTIONS=--max-old-space-size=7168
      - WORKER_ID=worker2
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
    gpus: all
    command: ["node", "dist/api-server.js"]
    restart: unless-stopped
    networks:
      - editly-network

  # Worker 3
  editly-worker3:
    container_name: editly-worker3
    image: editly/editly:latest
    ports:
      - "3003:3001"
    volumes:
      - "./outputs:/outputs"
      - "./uploads:/app/uploads"
      - "./temp:/app/temp"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - EXTERNAL_DOMAIN=https://editly.byinfant.com
      - USE_GPU=true
      - VIDEO_ENCODER=h264_nvenc
      - NVENC_PRESET=p1
      - NVENC_CQ=30
      - FFMPEG_THREADS=8
      - UV_THREADPOOL_SIZE=64
      - NODE_OPTIONS=--max-old-space-size=7168
      - WORKER_ID=worker3
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
    gpus: all
    command: ["node", "dist/api-server.js"]
    restart: unless-stopped
    networks:
      - editly-network

  # Worker 4
  editly-worker4:
    container_name: editly-worker4
    image: editly/editly:latest
    ports:
      - "3004:3001"
    volumes:
      - "./outputs:/outputs"
      - "./uploads:/app/uploads"
      - "./temp:/app/temp"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - EXTERNAL_DOMAIN=https://editly.byinfant.com
      - USE_GPU=true
      - VIDEO_ENCODER=h264_nvenc
      - NVENC_PRESET=p1
      - NVENC_CQ=30
      - FFMPEG_THREADS=8
      - UV_THREADPOOL_SIZE=64
      - NODE_OPTIONS=--max-old-space-size=7168
      - WORKER_ID=worker4
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
    gpus: all
    command: ["node", "dist/api-server.js"]
    restart: unless-stopped
    networks:
      - editly-network

  # Parallel Processor Coordinator
  parallel-processor:
    container_name: editly-parallel
    image: editly/editly:latest
    ports:
      - "3100:3100"
    volumes:
      - "./outputs:/outputs"
      - "./temp:/tmp"
    environment:
      - NODE_ENV=production
      - PARALLEL_PORT=3100
      - MAX_WORKERS=4
      - WORKER_BASE_PORT=3001
      - USE_GPU=true
      - CLEANUP_CHUNKS=false
    command: ["node", "dist/parallel-processor.js"]
    restart: unless-stopped
    networks:
      - editly-network
    depends_on:
      - editly-worker1
      - editly-worker2
      - editly-worker3
      - editly-worker4

networks:
  editly-network:
    driver: bridge

volumes:
  outputs:
    driver: local
  uploads:
    driver: local
  temp:
    driver: local